---
title: "AR"
output: html_notebook
---

```{r}
# Load libraries
rm(list=ls())
library(rjags)
library(bayesplot)
library(jagsUI)
library(kdensity)
library(loo)
library(gridExtra)
```

```{r}
# Load data
data = read.csv("../dataset/gdp_inflation.csv", header=T)
data$DATE         = as.Date(data$DATE)
data$GDP_PC1      = as.numeric(data$GDP_PC1)
data$CPIAUCSL_PC1 = as.numeric(data$CPIAUCSL_PC1)
```

### AR(1)
```{r}
# Define model in JAGS
modelAR.string <-"model {
  ## Parameters: alpha, tau, mu0
  # Likelihood 
  mu[1] <- Y[1]
  Yp[1] <- Y[1]
  for (i in 2:N) {
    Y[i]      ~  dnorm(mu[i], tau)
    mu[i]     <- mu0 + alpha * Y[i-1]
    Yp[i]     ~  dnorm(mu[i],tau)      # Prediction in sample
    LogLik[i] <- log(dnorm(Y[i], mu[i], tau)) 
  }
  
  # Prediction out of sample 
  ypOut[1] ~ dnorm(mu0 + alpha * Y[N], tau) 
  for(k in 2:Npred){
    ypOut[k] ~ dnorm(mu0 + alpha * ypOut[k-1], tau) 
  }
  sigma2 <- 1/tau
  
  # Prior 
  alpha ~ dunif(-1.0, 1.0)
  tau   ~ dgamma(2, 0.1)
  mu0   ~ dnorm(0.0, 1.0E-4)
}"
```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = round(0.1 * Ntot) # Horizon for out-of-sample prediction
N     = Ntot - Npred

data_subsample = data[1:N, ]

line_data_GDP <- list("N" = N,
                      "Npred" = Npred,
                      "Y" = data_subsample$GDP_PC1)

line_data_CPIAUCSL <- list("N" = N,
                           "Npred" = Npred,
                           "Y" = data_subsample$CPIAUCSL_PC1)

# JAGS
outputmcmcAR_GDP <- jags(model.file = textConnection(modelAR.string),
                         data = line_data_GDP,
                         parameters.to.save= c("alpha", "sigma2", "mu0", "Yp", "ypOut", "LogLik"), 
                         n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)

outputmcmcAR_CPIAUCSL <- jags(model.file = textConnection(modelAR.string),
                              data = line_data_CPIAUCSL,
                              parameters.to.save= c("alpha", "sigma2", "mu0", "Yp", "ypOut", "LogLik"), 
                              n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)
```

```{r}
# WAIC, DIC
WAIC_GDP <- waic(outputmcmcAR_GDP$sims.list$LogLik[,-1])
DIC_GDP  <- outputmcmcAR_GDP$DIC
WAIC_GDP
DIC_GDP

WAIC_CPIAUCSL <- waic(outputmcmcAR_CPIAUCSL$sims.list$LogLik[,-1])
DIC_CPIAUCSL  <- outputmcmcAR_CPIAUCSL$DIC
WAIC_CPIAUCSL
DIC_CPIAUCSL
```

```{r}
# Plot 1
p1 <- mcmc_areas(outputmcmcAR_GDP$samples, pars = c("mu0"),  prob = 0.95)
p2 <- mcmc_areas(outputmcmcAR_GDP$samples, pars = c("alpha"),  prob = 0.95)
p3 <- mcmc_areas(outputmcmcAR_GDP$samples, pars = c("sigma2"),  prob = 0.95)
p4 <- mcmc_areas(outputmcmcAR_CPIAUCSL$samples, pars = c("mu0"),  prob = 0.95)
p5 <- mcmc_areas(outputmcmcAR_CPIAUCSL$samples, pars = c("alpha"),  prob = 0.95)
p6 <- mcmc_areas(outputmcmcAR_CPIAUCSL$samples, pars = c("sigma2"),  prob = 0.95)
grid.arrange(p1, p2, p3, p4, p5, p6, ncol=3, nrow=2, top="Posterior distributions")

# Plot 2
p1 <- mcmc_trace(outputmcmcAR_GDP$samples, pars = c("mu0"))
p2 <- mcmc_trace(outputmcmcAR_GDP$samples, pars = c("alpha"))
p3 <- mcmc_trace(outputmcmcAR_GDP$samples, pars = c("sigma2"))
p4 <- mcmc_trace(outputmcmcAR_CPIAUCSL$samples, pars = c("mu0"))
p5 <- mcmc_trace(outputmcmcAR_CPIAUCSL$samples, pars = c("alpha"))
p6 <- mcmc_trace(outputmcmcAR_CPIAUCSL$samples, pars = c("sigma2"))
grid.arrange(p1, p2, p3, p4, p5, p6, ncol=3, nrow=2, top="Trace plots")

# Plot 3
autocorr.plot(outputmcmcAR_GDP$samples[,c("mu0")],main="mu0 GDP")
autocorr.plot(outputmcmcAR_GDP$samples[,c("alpha")],main="alpha GDP")
autocorr.plot(outputmcmcAR_GDP$samples[,c("sigma2")],main="sigma2 GDP")
autocorr.plot(outputmcmcAR_CPIAUCSL$samples[,c("mu0")],main="mu0 CPIAUCSL")
autocorr.plot(outputmcmcAR_CPIAUCSL$samples[,c("alpha")],main="alpha CPIAUCSL")
autocorr.plot(outputmcmcAR_CPIAUCSL$samples[,c("sigma2")],main="sigma2 CPIAUCSL")
```

```{r}
# Get parameters information
mu0_GDP    <- cbind(inf = mean(outputmcmcAR_GDP$q2.5$mu0), 
                    center = mean(outputmcmcAR_GDP$mean$mu0),
                    sup = mean(outputmcmcAR_GDP$q97.5$mu0))
alpha_GDP  <- cbind(inf = mean(outputmcmcAR_GDP$q2.5$alpha), 
                    center = mean(outputmcmcAR_GDP$mean$alpha),
                    sup = mean(outputmcmcAR_GDP$q97.5$alpha))
sigma2_GDP <- cbind(inf = mean(outputmcmcAR_GDP$q2.5$sigma2), 
                    center = mean(outputmcmcAR_GDP$mean$sigma2),
                    sup = mean(outputmcmcAR_GDP$q97.5$sigma2))
mu0_CPIAUCSL    <- cbind(inf = mean(outputmcmcAR_CPIAUCSL$q2.5$mu0), 
                         center = mean(outputmcmcAR_CPIAUCSL$mean$mu0),
                         sup = mean(outputmcmcAR_CPIAUCSL$q97.5$mu0))
alpha_CPIAUCSL  <- cbind(inf = mean(outputmcmcAR_CPIAUCSL$q2.5$alpha), 
                         center = mean(outputmcmcAR_CPIAUCSL$mean$alpha),
                         sup = mean(outputmcmcAR_CPIAUCSL$q97.5$alpha))
sigma2_CPIAUCSL <- cbind(inf = mean(outputmcmcAR_CPIAUCSL$q2.5$sigma2), 
                         center = mean(outputmcmcAR_CPIAUCSL$mean$sigma2),
                         sup = mean(outputmcmcAR_CPIAUCSL$q97.5$sigma2))
models.parameters <- rbind(mu0_GDP, alpha_GDP, sigma2_GDP, mu0_CPIAUCSL, alpha_CPIAUCSL, sigma2_CPIAUCSL)
rownames(models.parameters) <- c("mu0_GDP", "alpha_GDP", "sigma2_GDP", 
                                 "mu0_CPIAUCSL", "alpha_CPIAUCSL", "sigma2_CPIAUCSL")
models.parameters
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp      = outputmcmcAR_GDP$mean$Yp
q1      = outputmcmcAR_GDP$q2.5$Yp
q2      = outputmcmcAR_GDP$q97.5$Yp
yp_pred = outputmcmcAR_GDP$mean$ypOut
q1_pred = outputmcmcAR_GDP$q2.5$ypOut
q2_pred = outputmcmcAR_GDP$q97.5$ypOut

# Plot
plot(t, data$GDP_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
     type="l", main= "Prediction GDP_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# AR model using arima function
AR_gdp     <- arima(data_subsample$GDP_PC1, order = c(1,0,0))
AR_gdp_fit <- data_subsample$GDP_PC1 - residuals(AR_gdp)
print(AR_gdp)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "AR Model In-Sample Predictions",
     ylab = "GDP_PC1", xlab = "t")
points(as.vector(AR_gdp_fit), col = "red3")
lines(data$GDP_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot 2 (Posterior of alpha)
alpha.mcmc.mat=as.matrix(outputmcmcAR_GDP$samples[,c("alpha")], iters = FALSE)
yalpha=kdensity(alpha.mcmc.mat)
plot(yalpha, main="Posterior of alpha")
abline(v=outputmcmcAR_GDP$mean$alpha,col="blue")
abline(v=AR_gdp$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1)

# Plot 3 (Prediction ARIMA)
predict_gdp <- predict(AR_gdp, n.ahead=30)
predict_gdp$pred
ts.plot(data$GDP_PC, ylab="y_t", main="ARIMA vs True data")
points(AR_gdp_fit, type = "l", col = 2, lty = 2)
points(predict_gdp$pred, type = "l", col = 'green2', lty = 2)
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp=outputmcmcAR_CPIAUCSL$mean$Yp
q1=outputmcmcAR_CPIAUCSL$q2.5$Yp
q2=outputmcmcAR_CPIAUCSL$q97.5$Yp
yp_pred=outputmcmcAR_CPIAUCSL$mean$ypOut
q1_pred=outputmcmcAR_CPIAUCSL$q2.5$ypOut
q2_pred=outputmcmcAR_CPIAUCSL$q97.5$ypOut

# Plot
plot(t, data$CPIAUCSL_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 17),
     type="l", main= "Prediction CPIAUCSL_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# AR model using arima function
AR_infl     <- arima(data_subsample$CPIAUCSL_PC1, order = c(1,0,0))
AR_infl_fit <- data_subsample$CPIAUCSL_PC1 - residuals(AR_infl)
print(AR_infl)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "AR Model In-Sample Predictions",
     ylab = "CPIAUCSL_PC1", xlab = "t")
points(as.vector(AR_infl_fit), col = "red3")
lines(data$CPIAUCSL_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot 2 (Posterior of alpha)
alpha.mcmc.mat=as.matrix(outputmcmcAR_CPIAUCSL$samples[,c("alpha")], iters = FALSE)
yalpha=kdensity(alpha.mcmc.mat)
plot(yalpha, main="Posterior of alpha")
abline(v=outputmcmcAR_CPIAUCSL$mean$alpha,col="blue")
abline(v=AR_infl$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1)

# Plot 3 (Prediction ARIMA)
predict_infl <- predict(AR_infl, n.ahead=30)
predict_infl$pred
ts.plot(data$CPIAUCSL_PC1, ylab="y_t", main="ARIMA vs True data")
points(AR_infl_fit, type = "l", col = 2, lty = 2)
points(predict_infl$pred, type = "l", col = 'green2', lty = 2)
```