---
title: "GARCH"
output: html_document
---

```{r}
# Load libraries
rm(list=ls())
library(rjags)
library(bayesplot)
library(jagsUI)
library(rugarch)
library(loo)
```

```{r}
# Load data
data = read.csv("../dataset/gdp_inflation.csv", header=T)
data$DATE         = as.Date(data$DATE)
data$GDP_PC1      = as.numeric(data$GDP_PC1)
data$CPIAUCSL_PC1 = as.numeric(data$CPIAUCSL_PC1)
```

### GARCH(1,1)
```{r}
# Define model in JAGS
modelGARCH.string <-"model {
  # Likelihood
  Yp[1]     <- Y[1]
  mu[1]     <- Y[1]
  tau[1]    <- 1 / sigma2[1]
  sigma2[1] <- a[1]
  eps2[1]   <- (Y[1] - mu[1]) * (Y[1] - mu[1])
  for(i in 2:N) {
    Y[i]      ~ dnorm(mu[i], tau[i])
    Yp[i]     ~ dnorm(mu[i], tau[i])      # Prediction in sample
    mu[i]     <- mu0 + alpha * Y[i-1]
    tau[i]    <- 1 / sigma2[i]
    sigma2[i] <- a[1] + a[2] * eps2[i-1] + a[3] * sigma2[i-1]
    eps2[i]   <- (Y[i] - mu[i]) * (Y[i] - mu[i])
    LogLik[i] <- log(dnorm(Y[i], mu[i], tau[i])) 
  }
  
  # Prediction out of sample 
  ypOut[1]     ~  dnorm(muOut[1], tauOut[1])
  muOut[1]     <- mu0 + alpha * Y[N]
  tauOut[1]    <- 1 / sigma2Out[1]
  sigma2Out[1] <- a[1] + a[2] * eps2[N] + a[3] * sigma2[N]
  eps2Out[1]   <- (ypOut[1] - muOut[1]) * (ypOut[1] - muOut[1])
  for (k in 2:Npred) {
    ypOut[k]     ~  dnorm(muOut[k], tauOut[k])
    muOut[k]     <- mu0 + alpha * ypOut[k-1]
    tauOut[k]    <- 1 / sigma2Out[k]
    sigma2Out[k] <- a[1] + a[2] * eps2Out[k-1] + a[3] * sigma2Out[k-1]
    eps2Out[k]   <- (ypOut[k] - muOut[k]) * (ypOut[k] - muOut[k])
  }
  
  # Prior 
  for(j in 1:3) {
    a[j] ~ dgamma(0.01, 0.01)
  }
  alpha ~ dunif(-1, 1)
  mu0   ~ dnorm(0.0, 1.0E-4)
}"
```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = round(0.1 * Ntot) # Horizon for out-of-sample prediction
N     = Ntot - Npred

data_subsample = data[1:N, ]

line_data_GDP <- list("N" = N,
                      "Npred" = Npred,
                      "Y" = data_subsample$GDP_PC1)

line_data_CPIAUCSL <- list("N" = N,
                           "Npred" = Npred,
                           "Y" = data_subsample$CPIAUCSL_PC1)

# JAGS
outputmcmcGARCH_GDP <- jags(model.file = textConnection(modelGARCH.string),
                         data = line_data_GDP,
                         parameters.to.save= c("a", "alpha", "sigma2", "mu0", "Yp", "ypOut", "LogLik"), 
                         n.adapt=1000, n.iter=10000, n.chains = 1, n.burnin = 1000)

outputmcmcGARCH_CPIAUCSL <- jags(model.file = textConnection(modelGARCH.string),
                              data = line_data_CPIAUCSL,
                              parameters.to.save= c("a", "alpha", "sigma2", "mu0", "Yp", "ypOut", "LogLik"), 
                              n.adapt=1000, n.iter=10000, n.chains = 1, n.burnin = 1000)
```

```{r}
# WAIC, DIC
WAIC_GDP <- waic(outputmcmcGARCH_GDP$sims.list$LogLik[,-1])
DIC_GDP  <- outputmcmcGARCH_GDP$DIC
WAIC_GDP
DIC_GDP

WAIC_CPIAUCSL <- waic(outputmcmcGARCH_CPIAUCSL$sims.list$LogLik[,-1])
DIC_CPIAUCSL  <- outputmcmcGARCH_CPIAUCSL$DIC
WAIC_CPIAUCSL
DIC_CPIAUCSL
```

```{r}
# Plot 1
p1  <- mcmc_areas(outputmcmcGARCH_GDP$samples, pars = c("mu0"),  prob = 0.95)
p2  <- mcmc_areas(outputmcmcGARCH_GDP$samples, pars = c("alpha"),  prob = 0.95)
p3  <- mcmc_areas(outputmcmcGARCH_GDP$samples, pars = c("a[1]"),  prob = 0.95)
p4  <- mcmc_areas(outputmcmcGARCH_GDP$samples, pars = c("a[2]"),  prob = 0.95)
p5  <- mcmc_areas(outputmcmcGARCH_GDP$samples, pars = c("a[3]"),  prob = 0.95)
p6  <- mcmc_areas(outputmcmcGARCH_CPIAUCSL$samples, pars = c("mu0"),  prob = 0.95)
p7  <- mcmc_areas(outputmcmcGARCH_CPIAUCSL$samples, pars = c("alpha"),  prob = 0.95)
p8  <- mcmc_areas(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[1]"),  prob = 0.95)
p9  <- mcmc_areas(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[2]"),  prob = 0.95)
p10 <- mcmc_areas(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[3]"),  prob = 0.95)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, ncol=5, nrow=2, top="Posterior distributions")

# Plot 2
p1  <- mcmc_trace(outputmcmcGARCH_GDP$samples, pars = c("mu0"))
p2  <- mcmc_trace(outputmcmcGARCH_GDP$samples, pars = c("alpha"))
p3  <- mcmc_trace(outputmcmcGARCH_GDP$samples, pars = c("a[1]"))
p4  <- mcmc_trace(outputmcmcGARCH_GDP$samples, pars = c("a[2]"))
p5  <- mcmc_trace(outputmcmcGARCH_GDP$samples, pars = c("a[3]"))
p6  <- mcmc_trace(outputmcmcGARCH_CPIAUCSL$samples, pars = c("mu0"))
p7  <- mcmc_trace(outputmcmcGARCH_CPIAUCSL$samples, pars = c("alpha"))
p8  <- mcmc_trace(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[1]"))
p9  <- mcmc_trace(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[2]"))
p10 <- mcmc_trace(outputmcmcGARCH_CPIAUCSL$samples, pars = c("a[3]"))
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, ncol=2, nrow=5, top="Trace plots")

# Plot 3
autocorr.plot(outputmcmcGARCH_GDP$samples[,c("mu0")],main="mu0 GDP")
autocorr.plot(outputmcmcGARCH_GDP$samples[,c("alpha")],main="alpha GDP")
autocorr.plot(outputmcmcGARCH_GDP$samples[,c("a[1]")],main="a[1] GDP")
autocorr.plot(outputmcmcGARCH_GDP$samples[,c("a[2]")],main="a[2] GDP")
autocorr.plot(outputmcmcGARCH_GDP$samples[,c("a[3]")],main="a[3] GDP")
autocorr.plot(outputmcmcGARCH_CPIAUCSL$samples[,c("mu0")],main="mu0 CPIAUCSL")
autocorr.plot(outputmcmcGARCH_CPIAUCSL$samples[,c("alpha")],main="alpha CPIAUCSL")
autocorr.plot(outputmcmcGARCH_CPIAUCSL$samples[,c("a[1]")],main="a[1] CPIAUCSL")
autocorr.plot(outputmcmcGARCH_CPIAUCSL$samples[,c("a[2]")],main="a[2] CPIAUCSL")
autocorr.plot(outputmcmcGARCH_CPIAUCSL$samples[,c("a[3]")],main="a[3] CPIAUCSL")

plot(outputmcmcGARCH_GDP$mean$sigma2, main = "sigma^2 GDP", ylab = "sigma^2", xlab = "Time")
plot(outputmcmcGARCH_CPIAUCSL$mean$sigma2, main = "sigma^2 CPIAUCSL", ylab = "sigma^2", xlab = "Time")
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp=outputmcmcGARCH_GDP$mean$Yp
q1=outputmcmcGARCH_GDP$q2.5$Yp
q2=outputmcmcGARCH_GDP$q97.5$Yp
yp_pred=outputmcmcGARCH_GDP$mean$ypOut
q1_pred=outputmcmcGARCH_GDP$q2.5$ypOut
q2_pred=outputmcmcGARCH_GDP$q97.5$ypOut

# Plot
plot(t, data$GDP_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
     type="l", main= "Prediction GDP_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# GARCH model using ugarchfit function
garch_spec <- ugarchspec(
  variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(1, 0), include.mean = TRUE),
  distribution.model = "norm"
)
fit_garch  <- ugarchfit(spec = garch_spec, data = data_subsample$GDP_PC1)
fit_garch
in_sample_predictions <- fitted(fit_garch)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "GARCH Model In-Sample Predictions",
     ylab = "GDP_PC1", xlab = "t")
points(as.vector(in_sample_predictions[,1]), col = "red3")
lines(data$GDP_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "sGARCH", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot out-of-sample predictions
forecast = ugarchforecast(fit_garch, n.ahead=Npred, data=data_subsample$GDP_PC1)
plot(yp_pred, type = "p", col = "green3", main = "GARCH Model Out-of-Sample Predictions",
     ylab = "GDP_PC1", xlab = "t", ylim=c(0, 12))
points(as.vector(fitted(forecast)), col = "red")
lines(data$GDP_PC1[276:(276+Npred)], col = "blue")
legend("topright", legend = c("JAGS", "sGARCH", "data"),
       col = c("green3", "red", "blue"), lty = 1)

# Compute mean square errors
mean((yp - as.vector(in_sample_predictions))^2)
mean((yp_pred - as.vector(fitted(forecast)))^2)

# Plot posterior of a[1]
a1.mcmc.mat=as.matrix(outputmcmcGARCH_GDP$samples[,c("a[1]")], iters = FALSE)
ya1=kdensity(a1.mcmc.mat)
plot(ya1, main="Posterior of a[1]")
abline(v=outputmcmcGARCH_GDP$mean$a[1],col="blue")
abline(v=coef(fit_garch)[3],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of a[2]
a2.mcmc.mat=as.matrix(outputmcmcGARCH_GDP$samples[,c("a[2]")], iters = FALSE)
ya2=kdensity(a2.mcmc.mat)
plot(ya2,main="Posterior of a[2]")
abline(v=outputmcmcGARCH_GDP$mean$a[2],col="blue")
abline(v=coef(fit_garch)[4],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of a[3]
a3.mcmc.mat=as.matrix(outputmcmcGARCH_GDP$samples[,c("a[3]")], iters = FALSE)
ya3=kdensity(a3.mcmc.mat)
plot(ya3,main="Posterior of a[3]")
abline(v=outputmcmcGARCH_GDP$mean$a[3],col="blue")
abline(v=coef(fit_garch)[5],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of alpha
alpha.mcmc.mat=as.matrix(outputmcmcGARCH_GDP$samples[,c("alpha")], iters = FALSE)
yalpha=kdensity(alpha.mcmc.mat)
plot(yalpha,main="Posterior of alpha")
abline(v=outputmcmcGARCH_GDP$mean$alpha,col="blue")
abline(v=coef(fit_garch)[2],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp=outputmcmcGARCH_CPIAUCSL$mean$Yp
q1=outputmcmcGARCH_CPIAUCSL$q2.5$Yp
q2=outputmcmcGARCH_CPIAUCSL$q97.5$Yp
yp_pred=outputmcmcGARCH_CPIAUCSL$mean$ypOut
q1_pred=outputmcmcGARCH_CPIAUCSL$q2.5$ypOut
q2_pred=outputmcmcGARCH_CPIAUCSL$q97.5$ypOut

# Plot
plot(t, data$CPIAUCSL_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 17),
     type="l", main= "Prediction CPIAUCSL_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# GARCH model using ugarchfit function
garch_spec <- ugarchspec(
  variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(1, 0), include.mean = TRUE),
  distribution.model = "norm"
)
fit_garch  <- ugarchfit(spec = garch_spec, data = data_subsample$CPIAUCSL_PC1)
fit_garch
in_sample_predictions <- fitted(fit_garch)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "GARCH Model In-Sample Predictions",
     ylab = "CPIAUCSL_PC1", xlab = "t")
points(as.vector(in_sample_predictions[,1]), col = "red3")
lines(data$CPIAUCSL_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "sGARCH", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot out-of-sample predictions
forecast = ugarchforecast(fit_garch, n.ahead=Npred, data=data_subsample$GDP_PC1)
plot(yp_pred, type = "p", col = "green3", main = "GARCH Model Out-of-Sample Predictions",
     ylab = "CPIAUCSL_PC1", xlab = "t", ylim=c(0, 12))
points(as.vector(fitted(forecast)), col = "red")
lines(data$CPIAUCSL_PC1[276:(276+Npred)], col = "blue")
legend("topright", legend = c("JAGS", "sGARCH", "data"),
       col = c("green3", "red", "blue"), lty = 1)

# Compute mean square errors
mean((yp - as.vector(in_sample_predictions))^2)
mean((yp_pred - as.vector(fitted(forecast)))^2)

# Plot posterior of a[1]
a1.mcmc.mat=as.matrix(outputmcmcGARCH_CPIAUCSL$samples[,c("a[1]")], iters = FALSE)
ya1=kdensity(a1.mcmc.mat)
plot(ya1,main="Posterior of a[1]")
abline(v=outputmcmcGARCH_CPIAUCSL$mean$a[1],col="blue")
abline(v=coef(fit_garch)[3],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of a[2]
a2.mcmc.mat=as.matrix(outputmcmcGARCH_CPIAUCSL$samples[,c("a[2]")], iters = FALSE)
ya2=kdensity(a2.mcmc.mat)
plot(ya2,main="Posterior of a[2]")
abline(v=outputmcmcGARCH_CPIAUCSL$mean$a[2],col="blue")
abline(v=coef(fit_garch)[4],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of a[3]
a3.mcmc.mat=as.matrix(outputmcmcGARCH_CPIAUCSL$samples[,c("a[3]")], iters = FALSE)
ya3=kdensity(a3.mcmc.mat)
plot(ya3,main="Posterior of a[3]")
abline(v=outputmcmcGARCH_CPIAUCSL$mean$a[3],col="blue")
abline(v=coef(fit_garch)[5],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)

# Plot posterior of alpha
alpha.mcmc.mat=as.matrix(outputmcmcGARCH_CPIAUCSL$samples[,c("alpha")], iters = FALSE)
yalpha=kdensity(alpha.mcmc.mat)
plot(yalpha,main="Posterior of alpha")
abline(v=outputmcmcGARCH_CPIAUCSL$mean$alpha,col="blue")
abline(v=coef(fit_garch)[2],col="red")
legend("topright", legend = c("JAGS", "sGARCH"),
       col = c("blue", "red"), lty = 1)
```