---
title: "MA"
output: html_notebook
---


```{r}
# Load libraries
rm(list=ls())
library(rjags)
library(bayesplot)
library(jagsUI)
library(kdensity)
library(loo)
library(gridExtra)
```

```{r}
# Load data
data = read.csv("../dataset/gdp_inflation.csv", header=T)
data$DATE         = as.Date(data$DATE)
data$GDP_PC1      = as.numeric(data$GDP_PC1)
data$CPIAUCSL_PC1 = as.numeric(data$CPIAUCSL_PC1)
```

### MA(1)
```{r}
# Define model in JAGS
modelMA.string <-"model {
## Parameters: alpha, tau, mu0
  # Likelihood 
  Yp[1]  <- mu[1]
  mu[1]  <- Y[1]
  eps[1] <- Y[1] - mu[1]
  for (i in 2:N) {
    Y[i]   ~  dnorm(mu[i], tau)
    mu[i]  <- mu0 + theta * eps[i-1]
    eps[i] <- Y[i] - mu[i]
    Yp[i]  ~  dnorm(mu[i], tau) 
    LogLik[i] <- log(dnorm(Y[i], mu[i], tau)) 
  }
  
  # prediction out of sample 
  ypOut[1]  ~  dnorm(mu0+theta*eps[N],tau) 
  muOut[1]  <- mu0+theta*eps[N]
  epsOut[1] <- ypOut[1] - muOut[1] 
  for(k in 2:Npred){
    ypOut[k]  ~  dnorm(mu0+theta*epsOut[k-1],tau) 
    muOut[k]  <- mu0+theta*epsOut[k-1]
    epsOut[k] <- ypOut[k] - muOut[k]
  }
  
  sigma2<-1/tau
  #prior 
  theta ~ dunif(-1.0, 1.0)
  tau   ~ dgamma(2, 0.1)
  mu0    ~ dnorm(0.0, 1.0E-4)
}"
```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = round(0.1 * Ntot) # Horizon for out-of-sample prediction
N     = Ntot - Npred

data_subsample = data[1:N, ]

line_data_GDP <- list("N" = N,
                      "Npred" = Npred,
                      "Y" = data_subsample$GDP_PC1)

line_data_CPIAUCSL <- list("N" = N,
                           "Npred" = Npred,
                           "Y" = data_subsample$CPIAUCSL_PC1)
# JAGS
outputmcmcMA_GDP <- jags(model.file = textConnection(modelMA.string),
                         data = line_data_GDP,
                         parameters.to.save= c("theta", "sigma2", "eps", "mu0", "Yp", "ypOut", "LogLik"), 
                         n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)

outputmcmcMA_CPIAUCSL <- jags(model.file = textConnection(modelMA.string),
                              data = line_data_CPIAUCSL,
                              parameters.to.save= c("theta", "sigma2", "eps", "mu0", "Yp", "ypOut", "LogLik"), 
                              n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)
```

```{r}
# WAIC, DIC
WAIC_GDP <- waic(outputmcmcMA_GDP$sims.list$LogLik[,-1])
DIC_GDP  <- outputmcmcMA_GDP$DIC
WAIC_GDP
DIC_GDP

WAIC_CPIAUCSL <- waic(outputmcmcMA_CPIAUCSL$sims.list$LogLik[,-1])
DIC_CPIAUCSL  <- outputmcmcMA_CPIAUCSL$DIC
WAIC_CPIAUCSL
DIC_CPIAUCSL
```

```{r}
# Plot 1
p1 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("mu0"),  prob = 0.95)
p2 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("theta"),  prob = 0.95)
p3 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("sigma2"),  prob = 0.95)
p4 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("mu0"),  prob = 0.95)
p5 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("theta"),  prob = 0.95)
p6 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("sigma2"),  prob = 0.95)
grid.arrange(p1, p2, p3, p4, p5, p6, ncol=3, nrow=2, top="Posterior distributions")

# Plot 2
p1 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("mu0"))
p2 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("theta"))
p3 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("sigma2"))
p4 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("mu0"))
p5 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("theta"))
p6 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("sigma2"))
grid.arrange(p1, p2, p3, p4, p5, p6, ncol=3, nrow=2, top="Trace plots")

# Plot 3
autocorr.plot(outputmcmcMA_GDP$samples[,c("mu0")],main="mu0 GDP")
autocorr.plot(outputmcmcMA_GDP$samples[,c("theta")],main="theta GDP")
autocorr.plot(outputmcmcMA_GDP$samples[,c("sigma2")],main="sigma2 GDP")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("mu0")],main="mu0 CPIAUCSL")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("theta")],main="theta CPIAUCSL")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("sigma2")],main="sigma2 CPIAUCSL")
```

```{r}
# Get parameters information
mu0_GDP    <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$mu0), 
                    center = mean(outputmcmcMA_GDP$mean$mu0),
                    sup = mean(outputmcmcMA_GDP$q97.5$mu0))
theta_GDP  <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$theta), 
                    center = mean(outputmcmcMA_GDP$mean$theta),
                    sup = mean(outputmcmcMA_GDP$q97.5$theta))
sigma2_GDP <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$sigma2), 
                    center = mean(outputmcmcMA_GDP$mean$sigma2),
                    sup = mean(outputmcmcMA_GDP$q97.5$sigma2))
mu0_CPIAUCSL    <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$mu0), 
                         center = mean(outputmcmcMA_CPIAUCSL$mean$mu0),
                         sup = mean(outputmcmcMA_CPIAUCSL$q97.5$mu0))
theta_CPIAUCSL  <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$theta), 
                         center = mean(outputmcmcMA_CPIAUCSL$mean$theta),
                         sup = mean(outputmcmcMA_CPIAUCSL$q97.5$theta))
sigma2_CPIAUCSL <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$sigma2), 
                         center = mean(outputmcmcMA_CPIAUCSL$mean$sigma2),
                         sup = mean(outputmcmcMA_CPIAUCSL$q97.5$sigma2))
models.parameters <- rbind(mu0_GDP, theta_GDP, sigma2_GDP, mu0_CPIAUCSL, theta_CPIAUCSL, sigma2_CPIAUCSL)
rownames(models.parameters) <- c("mu0_GDP", "theta_GDP", "sigma2_GDP", 
                                 "mu0_CPIAUCSL", "theta_CPIAUCSL", "sigma2_CPIAUCSL")
models.parameters
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)


yp      = outputmcmcMA_GDP$mean$Yp
q1      = outputmcmcMA_GDP$q2.5$Yp
q2      = outputmcmcMA_GDP$q97.5$Yp
yp_pred = outputmcmcMA_GDP$mean$ypOut
q1_pred = outputmcmcMA_GDP$q2.5$ypOut
q2_pred = outputmcmcMA_GDP$q97.5$ypOut

# Plot
plot(t, data$GDP_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
     type="l", main= "Prediction GDP_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# MA model using arima function
MA_gdp <- arima(data_subsample$GDP_PC1, order = c(0,0,1))
MA_gdp_fit <- data_subsample$GDP_PC1 - residuals(MA_gdp)
print(MA_gdp)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "MA(1) Model In-Sample Predictions",
     ylab = "GDP_PC1", xlab = "t")
points(as.vector(MA_gdp_fit), col = "red3")
lines(data$GDP_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot 2 (Posterior of theta)
theta.mcmc.mat=as.matrix(outputmcmcMA_GDP$samples[,c("theta")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta")
abline(v=outputmcmcMA_GDP$mean$theta,col="blue")
abline(v=MA_gdp$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1)

# Plot 3 (Prediction ARIMA)
predict_gdp <- predict(MA_gdp, n.ahead=30)
predict_gdp$pred
ts.plot(data$GDP_PC, ylab="y_t", main="ARIMA vs True data")
points(MA_gdp_fit, type = "l", col = 2, lty = 2)
points(predict_gdp$pred, type = "l", col = 'green2', lty = 2)


```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp      = outputmcmcMA_CPIAUCSL$mean$Yp
q1      = outputmcmcMA_CPIAUCSL$q2.5$Yp
q2      = outputmcmcMA_CPIAUCSL$q97.5$Yp
yp_pred = outputmcmcMA_CPIAUCSL$mean$ypOut
q1_pred = outputmcmcMA_CPIAUCSL$q2.5$ypOut
q2_pred = outputmcmcMA_CPIAUCSL$q97.5$ypOut

# Plot
plot(t, data$CPIAUCSL_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 17),
     type="l", main= "Prediction CPIAUCSL_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# AR model using arima function
MA_infl <- arima(data_subsample$CPIAUCSL_PC1, order = c(0,0,1))
MA_infl_fit <- data_subsample$CPIAUCSL_PC1 - residuals(MA_infl)
print(MA_infl)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "MA(1) Model In-Sample Predictions",
     ylab = "CPIAUCSL_PC1", xlab = "t")
points(as.vector(MA_infl_fit), col = "red3")
lines(data$CPIAUCSL_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot 2 (Posterior of theta)
theta.mcmc.mat=as.matrix(outputmcmcMA_CPIAUCSL$samples[,c("theta")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta", xlim = c(0.8,1))
abline(v=outputmcmcMA_CPIAUCSL$mean$theta,col="blue")
abline(v=MA_infl$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1)

# Plot 3 (Prediction ARIMA)
predict_infl <- predict(MA_infl, n.ahead=30)
predict_infl$pred
ts.plot(data$CPIAUCSL_PC1, ylab="y_t", main="ARIMA vs True data")
points(MA_infl_fit, type = "l", col = 2, lty = 2)
points(predict_infl$pred, type = "l", col = 'green2', lty = 2)
```

### MA(2)
```{r}
# Define model in JAGS
modelMA_q2.string <-"model {
## Parameters: alpha, tau, mu0
  # Likelihood 
  Yp[1] <- mu[1]
  mu[1] <- Y[1]
  eps[1] <- Y[1] - mu[1]
  Y[2] ~ dnorm(mu[2], tau)
  Yp[2] ~ dnorm(mu[2], tau)
  mu[2] <- mu0 + theta_1 * eps[1]
  eps[2] <- Y[2] - mu[2]
  for (i in 3:N) {
    Y[i] ~ dnorm(mu[i], tau)
    mu[i] <- mu0 + theta_1 * eps[i-1] + theta_2 * eps[i-2]
    eps[i] <- Y[i] - mu[i]
    Yp[i] ~ dnorm(mu[i], tau) 
    LogLik[i] <- log(dnorm(Y[i], mu[i], tau)) 
  }
  
  # prediction out of sample 
  ypOut[1] ~dnorm(muOut[1],tau) 
  muOut[1] <- mu0+theta_1*eps[N]+theta_2*eps[N-1]
  epsOut[1] <- ypOut[1] - muOut[1] 
  ypOut[2] ~dnorm(muOut[2],tau) 
  muOut[2] <- mu0+theta_1*epsOut[1]+theta_2*eps[N]
  epsOut[2] <- ypOut[2] - muOut[2] 
  for(k in 3:Npred){
    ypOut[k] ~ dnorm(muOut[k],tau) 
    muOut[k] <- mu0+theta_1*epsOut[k-1]+theta_2*epsOut[k-2]
    epsOut[k] <- ypOut[k] - muOut[k]
  }
  
  sigma2<-1/tau
  #prior 
  theta_1 ~ dunif(-1.5, 1.5)
  theta_2 ~ dunif(-1, 1)
  tau ~ dgamma(2, 0.1)
  mu0 ~ dnorm(0.0, 1.0E-4)
}"
```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = round(0.1 * Ntot) # Horizon for out-of-sample prediction
N     = Ntot - Npred

data_subsample = data[1:N, ]

line_data_GDP <- list("N" = N,
                      "Npred" = Npred,
                      "Y" = data_subsample$GDP_PC1)

line_data_CPIAUCSL <- list("N" = N,
                           "Npred" = Npred,
                           "Y" = data_subsample$CPIAUCSL_PC1)

# JAGS
outputmcmcMA_GDP <- jags(model.file = textConnection(modelMA_q2.string),
                         data = line_data_GDP,
                         parameters.to.save= c("theta_1", "theta_2", "sigma2", "eps", "mu0", "Yp", "ypOut", "LogLik"), 
                         n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)

outputmcmcMA_CPIAUCSL <- jags(model.file = textConnection(modelMA_q2.string),
                              data = line_data_CPIAUCSL,
                              parameters.to.save= c("theta_1", "theta_2", "sigma2", "eps", "mu0", "Yp", "ypOut", "LogLik"), 
                              n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)
```

```{r}
# WAIC, DIC
WAIC_GDP <- waic(outputmcmcMA_GDP$sims.list$LogLik[,-c(1,2)])
DIC_GDP  <- outputmcmcMA_GDP$DIC
WAIC_GDP
DIC_GDP

WAIC_CPIAUCSL <- waic(outputmcmcMA_CPIAUCSL$sims.list$LogLik[,-c(1,2)])
DIC_CPIAUCSL  <- outputmcmcMA_CPIAUCSL$DIC
WAIC_CPIAUCSL
DIC_CPIAUCSL
```

```{r}
# Plot 1
p1 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("mu0"),  prob = 0.95)
p2 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("theta_1"),  prob = 0.95)
p3 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("theta_2"),  prob = 0.95)
p4 <- mcmc_areas(outputmcmcMA_GDP$samples, pars = c("sigma2"),  prob = 0.95)
p5 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("mu0"),  prob = 0.95)
p6 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("theta_1"),  prob = 0.95)
p7 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("theta_2"),  prob = 0.95)
p8 <- mcmc_areas(outputmcmcMA_CPIAUCSL$samples, pars = c("sigma2"),  prob = 0.95)
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, ncol=4, nrow=2, top="Posterior distributions")

# Plot 2
p1 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("mu0"))
p2 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("theta_1"))
p3 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("theta_2"))
p4 <- mcmc_trace(outputmcmcMA_GDP$samples, pars = c("sigma2"))
p5 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("mu0"))
p6 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("theta_1"))
p7 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("theta_2"))
p8 <- mcmc_trace(outputmcmcMA_CPIAUCSL$samples, pars = c("sigma2"))
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, ncol=4, nrow=2, top="Trace plots")

# Plot 3
autocorr.plot(outputmcmcMA_GDP$samples[,c("mu0")],main="mu0 GDP")
autocorr.plot(outputmcmcMA_GDP$samples[,c("sigma2")],main="sigma2 GDP")
autocorr.plot(outputmcmcMA_GDP$samples[,c("theta_1")],main="theta1 GDP")
autocorr.plot(outputmcmcMA_GDP$samples[,c("theta_2")],main="theta2 GDP")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("mu0")],main="mu0 CPIAUCSL")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("sigma2")],main="sigma2 CPIAUCSL")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("theta_1")],main="theta1 CPIAUCSL")
autocorr.plot(outputmcmcMA_CPIAUCSL$samples[,c("theta_2")],main="theta2 CPIAUCSL")
```

```{r}
# Get parameters information
mu0_GDP    <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$mu0), 
                    center = mean(outputmcmcMA_GDP$mean$mu0),
                    sup = mean(outputmcmcMA_GDP$q97.5$mu0))
theta_1_GDP  <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$theta_1), 
                    center = mean(outputmcmcMA_GDP$mean$theta_1),
                    sup = mean(outputmcmcMA_GDP$q97.5$theta_1))
theta_2_GDP  <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$theta_2), 
                    center = mean(outputmcmcMA_GDP$mean$theta_2),
                    sup = mean(outputmcmcMA_GDP$q97.5$theta_2))
sigma2_GDP <- cbind(inf = mean(outputmcmcMA_GDP$q2.5$sigma2), 
                    center = mean(outputmcmcMA_GDP$mean$sigma2),
                    sup = mean(outputmcmcMA_GDP$q97.5$sigma2))
mu0_CPIAUCSL    <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$mu0), 
                         center = mean(outputmcmcMA_CPIAUCSL$mean$mu0),
                         sup = mean(outputmcmcMA_CPIAUCSL$q97.5$mu0))
theta_1_CPIAUCSL  <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$theta_1), 
                    center = mean(outputmcmcMA_CPIAUCSL$mean$theta_1),
                    sup = mean(outputmcmcMA_CPIAUCSL$q97.5$theta_1))
theta_2_CPIAUCSL  <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$theta_2), 
                    center = mean(outputmcmcMA_CPIAUCSL$mean$theta_2),
                    sup = mean(outputmcmcMA_CPIAUCSL$q97.5$theta_2))
sigma2_CPIAUCSL <- cbind(inf = mean(outputmcmcMA_CPIAUCSL$q2.5$sigma2), 
                         center = mean(outputmcmcMA_CPIAUCSL$mean$sigma2),
                         sup = mean(outputmcmcMA_CPIAUCSL$q97.5$sigma2))
models.parameters <- rbind(mu0_GDP, theta_1_GDP, theta_2_GDP, sigma2_GDP, 
                           mu0_CPIAUCSL, theta_1_CPIAUCSL, theta_2_CPIAUCSL, sigma2_CPIAUCSL)
rownames(models.parameters) <- c("mu0_GDP", "theta_1_GDP", "theta_2_GDP", "sigma2_GDP", 
                                 "mu0_CPIAUCSL", "theta_1_CPIAUCSL", "theta_2_CPIAUCSL", "sigma2_CPIAUCSL")
models.parameters
```

```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp      = outputmcmcMA_GDP$mean$Yp
q1      = outputmcmcMA_GDP$q2.5$Yp
q2      = outputmcmcMA_GDP$q97.5$Yp
yp_pred = outputmcmcMA_GDP$mean$ypOut
q1_pred = outputmcmcMA_GDP$q2.5$ypOut
q2_pred = outputmcmcMA_GDP$q97.5$ypOut

# Plot
plot(t, data$GDP_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
     type="l", main= "Prediction GDP_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```


```{r}
# MA(2) model using arima function
MA_gdp_q2 <- arima(data_subsample$GDP_PC1, order = c(0,0,2))
MA_gdp_q2_fit <- data_subsample$GDP_PC1 - residuals(MA_gdp_q2)
print(MA_gdp_q2)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "MA(2) Model In-Sample Predictions",
     ylab = "GDP_PC1", xlab = "t")
points(as.vector(MA_gdp_fit), col = "red3")
lines(data$GDP_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

# Plot 2 (Posterior of theta 1)
par(mfrow=c(1,2))
theta.mcmc.mat=as.matrix(outputmcmcMA_GDP$samples[,c("theta_1")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta 1", xlim=c(0.8,1.5))
abline(v=outputmcmcMA_GDP$mean$theta_1,col="blue")
abline(v=MA_gdp_q2$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1, cex=0.7)

# Plot 3 (Posterior of theta 2)
theta.mcmc.mat=as.matrix(outputmcmcMA_GDP$samples[,c("theta_2")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta 2", xlim=c(0.3, 0.8))
abline(v=outputmcmcMA_GDP$mean$theta_2,col="blue")
abline(v=MA_gdp_q2$coef[2],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1, cex=0.7)

par(mfrow=c(1,1))
# Plot 4 (Prediction ARIMA)
predict_gdp <- predict(MA_gdp_q2, n.ahead=30)
predict_gdp$pred
ts.plot(data$GDP_PC, ylab="y_t", main="ARIMA vs True data")
points(MA_gdp_q2_fit, type = "l", col = 2, lty = 2)
points(predict_gdp$pred, type = "l", col = 'green2', lty = 2)
```


```{r}
t  = seq(1,Ntot)
tt = seq(1,N)

yp      = outputmcmcMA_CPIAUCSL$mean$Yp
q1      = outputmcmcMA_CPIAUCSL$q2.5$Yp
q2      = outputmcmcMA_CPIAUCSL$q97.5$Yp
yp_pred = outputmcmcMA_CPIAUCSL$mean$ypOut
q1_pred = outputmcmcMA_CPIAUCSL$q2.5$ypOut
q2_pred = outputmcmcMA_CPIAUCSL$q97.5$ypOut

# Plot
plot(t, data$CPIAUCSL_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 17),
     type="l", main= "Prediction CPIAUCSL_PC1")
points(tt, yp, pch="*", col="red")
polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
points(seq((N+1),Ntot,1), pch="*", yp_pred, col="blue")
polygon(c(seq((N+1),Ntot,1), rev(seq((N+1),Ntot,1))), 
        c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
       xpd=TRUE, inset=c(0.005,0),
       legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
       col = c("black", "red", "blue"))
```

```{r}
# MA(2) model using arima function
MA_infl_q2 <- arima(data_subsample$CPIAUCSL_PC1, order = c(0,0,2))
MA_infl_q2_fit <- data_subsample$CPIAUCSL_PC1 - residuals(MA_infl_q2)
print(MA_infl_q2)

# Plot in-sample predictions
plot(yp, type = "p", col = "green3", main = "MA(2) Model In-Sample Predictions",
     ylab = "CPIAUCSL_PC1", xlab = "t")
points(as.vector(MA_infl_fit), col = "red3")
lines(data$CPIAUCSL_PC1[1:275], col = "blue")
legend("topright", legend = c("JAGS", "ARIMA", "data"),
       col = c("green3", "red3", "blue"), lty = 1)

par(mfrow=c(1,2))
# Plot 2 (Posterior of theta 1)
theta.mcmc.mat=as.matrix(outputmcmcMA_CPIAUCSL$samples[,c("theta_1")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta 1", xlim=c(1,1.7))
abline(v=outputmcmcMA_CPIAUCSL$mean$theta_1,col="blue")
abline(v=MA_infl_q2$coef[1],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1, cex=0.7)

# Plot 3 (Posterior of theta 2)
theta.mcmc.mat=as.matrix(outputmcmcMA_CPIAUCSL$samples[,c("theta_2")], iters = FALSE)
ytheta=kdensity(theta.mcmc.mat)
plot(ytheta,main="Posterior of theta 2", xlim=c(0.2,0.7))
abline(v=outputmcmcMA_CPIAUCSL$mean$theta_2,col="blue")
abline(v=MA_infl_q2$coef[2],col="red")
legend("topright", legend = c("JAGS", "ARIMA"),
       col = c("blue", "red"), lty = 1, cex=0.7)

par(mfrow=c(1,1))
# Plot 4 (Prediction ARIMA)
predict_infl <- predict(MA_infl_q2, n.ahead=30)
predict_infl$pred
ts.plot(data$CPIAUCSL_PC1, ylab="y_t", main="ARIMA vs True data")
points(MA_infl_q2_fit, type = "l", col = 2, lty = 2)
points(predict_infl$pred, type = "l", col = 'green2', lty = 2)
```