---
title: "Window Prediction for Covid"
output: html_notebook
---

```{r}
# Load libraries
rm(list=ls())
library(rjags)
library(bayesplot)
library(jagsUI)
library(kdensity)
```

```{r}
# Load data
data = read.csv("../dataset/gdp_inflation.csv", header=T)
data$DATE         = as.Date(data$DATE)
data$GDP_PC1      = as.numeric(data$GDP_PC1)
data$CPIAUCSL_PC1 = as.numeric(data$CPIAUCSL_PC1)
```

### ARMA(1,1)
```{r}
# Define model in JAGS
modelARMA.string <-"model {
  ## Parameters: alpha, tau, m0
  # Likelihood
  Yp[1]  <- mu[1]
  mu[1]  <- Y[1]
  eps[1] <- Y[1] - mu[1]
  for (i in 2:N) {
    Y[i]   ~ dnorm(mu[i], tau)
    Yp[i]  ~ dnorm(mu[i], tau)      # Prediction in sample
    mu[i]  <- m0 + alpha * Y[i-1] + theta * eps[i-1]
    eps[i] <- Y[i] - mu[i]
  }
  
  # Prediction out of sample 
  ypOut[1]  ~ dnorm(muOut[1], tau)
  muOut[1]  <- m0 + alpha * Y[N] + theta * eps[N]
  epsOut[1] <- ypOut[1] - muOut[1]
  for (k in 2:Npred) {
    ypOut[k] ~ dnorm(muOut[k], tau) 
    muOut[k] <- m0 + alpha * ypOut[k-1] + theta * epsOut[k-1]
    epsOut[k] <- ypOut[k] - muOut[k]
  }
  
  sigma2 <- 1/tau
  
  # Prior 
  alpha ~ dunif(-1, 1)
  theta ~ dunif(-1, 1)
  tau ~ dgamma(2, 0.1)
  m0    ~ dnorm(0.0, 1.0E-4)
}"
```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = 30 # Horizon for out-of-sample prediction
window <- 5
steps <- Npred/window
for(h in 0:(steps-1)){
  N     = Ntot - Npred + h*window
  
  data_subsample = data[1:N, ]
  
  line_data_GDP <- list("N" = N,
                        "Npred" = window,
                        "Y" = data_subsample$GDP_PC1)
  
  # JAGS
  outputmcmcARMA_GDP <- jags(model.file = textConnection(modelARMA.string),
                           data = line_data_GDP,
                           parameters.to.save= c("alpha", "theta", "sigma2", "m0", "Yp", "ypOut"), 
                           n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)
  
    t  = seq(1,Ntot)
    tt = seq(1,N)
    
    yp      = outputmcmcARMA_GDP$mean$Yp
    q1      = outputmcmcARMA_GDP$q2.5$Yp
    q2      = outputmcmcARMA_GDP$q97.5$Yp
    yp_pred = outputmcmcARMA_GDP$mean$ypOut
    q1_pred = outputmcmcARMA_GDP$q2.5$ypOut
    q2_pred = outputmcmcARMA_GDP$q97.5$ypOut
    
    # Plot prediction
    plot(t, data$GDP_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
         type="l", main= "Prediction GDP_PC1")
    points(tt, yp, pch="*", col="red")
    polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
    points(seq((N+1),(N+window),1), pch="*", yp_pred, col="blue")
    polygon(c(seq((N+1),(N+window),1), rev(seq((N+1),(N+window),1))), 
            c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
    legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
           xpd=TRUE, inset=c(0.005,0),
           legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
           col = c("black", "red", "blue"))
}
  

```

```{r}
# Prepare data
Ntot  = dim(data)[1]
Npred = 30 # Horizon for out-of-sample prediction
window <- 5
steps <- Npred/window
for(h in 0:(steps-1)){
  N     = Ntot - Npred + h*window
  
  data_subsample = data[1:N, ]
  
  line_data_CPIAUCSL <- list("N" = N,
                        "Npred" = window,
                        "Y" = data_subsample$CPIAUCSL_PC1)
  
  # JAGS
  outputmcmcARMA_CPIAUCSL <- jags(model.file = textConnection(modelARMA.string),
                           data = line_data_CPIAUCSL,
                           parameters.to.save= c("alpha", "theta", "sigma2", "m0", "Yp", "ypOut"), 
                           n.adapt=1000, n.iter=10000, n.chains = 3, n.burnin = 1000)
  
    t  = seq(1,Ntot)
    tt = seq(1,N)
    
    yp      = outputmcmcARMA_CPIAUCSL$mean$Yp
    q1      = outputmcmcARMA_CPIAUCSL$q2.5$Yp
    q2      = outputmcmcARMA_CPIAUCSL$q97.5$Yp
    yp_pred = outputmcmcARMA_CPIAUCSL$mean$ypOut
    q1_pred = outputmcmcARMA_CPIAUCSL$q2.5$ypOut
    q2_pred = outputmcmcARMA_CPIAUCSL$q97.5$ypOut
    
    # Plot prediction
    plot(t, data$CPIAUCSL_PC1, col="black", ylab="mu_t", ylim=c(-7.0, 24),
         type="l", main= "Prediction CPIAUCSL_PC1")
    points(tt, yp, pch="*", col="red")
    polygon(c(tt, rev(tt)), c(q1, rev(q2)), col = rgb(1, 0, 0, 0.3), border = NA)
    points(seq((N+1),(N+window),1), pch="*", yp_pred, col="blue")
    polygon(c(seq((N+1),(N+window),1), rev(seq((N+1),(N+window),1))), 
            c(q1_pred, rev(q2_pred)), col = rgb(0, 0, 1, 0.3), border = NA)
    legend("topright", lty = 0, bty="n", cex=0.8, pch = 19,
           xpd=TRUE, inset=c(0.005,0),
           legend = c("Dataset", "In-sample preditction", "Out-of-sample prediction"), 
           col = c("black", "red", "blue"))
}
  

```




